source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TencentQQSDK_Example', :exclusive => true do
  pod "TencentQQSDK", :path => "../"
end

target 'TencentQQSDK_Tests', :exclusive => true do
  pod "TencentQQSDK", :path => "../"

  
end
